### ISSUE TITLE
Add IE11 support

### ISSUE THREAD

**Issue by abdonrd** [Polymer/pwa-starter-kit-hn#14]
<img width="1355" alt="screen shot 2018-02-09 at 17 05 07" src="https://user-images.githubusercontent.com/1007051/36036908-763f5cf4-0dbb-11e8-939c-ae4b8feeef4b.png">

**Comment by abdonrd** [comment]
We could add [autoprefixer](https://github.com/postcss/autoprefixer) to the build step.

**Comment by keanulee** [comment]
Of all the many and burdensome issues with IE, CSS prefixes is actually not one of them. The issues are mainly around JS modules, the ES6 requirement for Custom Elements, and fetch/Promise polyfills. The (outdated) es5-webpack branch shows one approach to get it work using webpack for module loading and ce-adapter.

**Comment by abdonrd** [comment]
Yes yes, I only added the autoprefixer later thinking about the `flex` prefixes.

**Comment by keanulee** [comment]
Blocked on https://github.com/Polymer/lit-element/issues/45
